# Generated by Django 2.1.7 on 2019-07-23 07:30

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purpose_category',
            name='category',
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('study', 'StudyRoom'), ('performance', 'PerformanceRoom'), ('practice', 'PracticeRoom'), ('etc', 'etc')], default='study', max_length=50),
        ),
        migrations.AlterField(
            model_name='purpose_category',
            name='etc_what',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
