# Generated by Django 2.1.7 on 2019-07-23 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20190723_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='etc_what',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
