# Generated by Django 2.1.7 on 2019-07-23 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_post_etc_what'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Purpose_category',
        ),
    ]
