# Generated by Django 2.1.7 on 2019-07-24 08:13

from django.db import migrations, models
import multiselectfield.db.fields
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_post_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('study', 'StudyRoom'), ('performance', 'PerformanceRoom'), ('practice', 'PracticeRoom'), ('etc', 'etc')], max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='location',
            field=models.CharField(choices=[('서울특별시', '서울특별시'), ('부산광역시', '부산광역시'), ('세종특별시', '세종특별시'), ('충청북도', '충청북도'), ('충청남도', '충청남도'), ('전라북도', '전라북도'), ('전라남도', '전라남도'), ('대구광역시', '대구광역시'), ('제주특별시', '제주특별시'), ('경상북도', '경상북도'), ('경상남도', '경상남도')], default=post.models.default_city, max_length=30),
        ),
    ]
